set(SRC_FILES
  src/code_version.f90
  src/modules.f90
  src/vsop.f90
  src/data.f90
  src/functions.f90
  src/coordinates.f90
  src/nutation.f90
  src/sun.f90
  src/planets.f90
  src/moon_position.f90
  src/moon_routines.f90
  src/comets.f90
  src/asteroids.f90
  src/stars.f90
  src/riset.f90
  src/date_time.f90
  src/visibility.f90
  )
